= Em002-2.2 OSS Analysis and Preparation Checklist
:lang: en
:toc:
:sectnums:
:toclevels: 3
:sectnumlevels: 3
:experimental:
:revnumber: 1.0
:revdate: 14.09.2026

This checklist is part of _Em002-2 Instructions for Publishing Open Source Software_ and is intended for ICT professionals. +
It serves to review the documentation and source code of a project. In doing so, it helps ensure that the quality level of the documentation is sufficient to publish an application as open source. It can also be used to verify that the source code and all third-party components used by the project do not pose any legal risks. These measures minimise security risks. +
Information about this checklist can be found in _[Em002-2]_ in Section 4.

Furthermore, this checklist ensures that the project documentation addresses both end users and technical professionals equally.

== Subject matter

=== Name and brief description of the software

Enter the name of the software.

[cols="1"]
|===
a|

|===

=== Contact person and review

Name the organisation, contact person from the specialist office and the persons responsible (e.g. ISBO/DSBO) who have verified compliance with the publication requirements.

[cols="1"]
|===
a|

|===

== Checklist

[cols="1,6"]
|===
|☐
|_Em002-2.1 OSS Preliminary Assessment Checklist_ has been completed and no problematic points were identified.

|☐
a|
The source code to be published has been analysed.

* Review how the existing code quality and guidelines have been implemented.
* Ensure no sensitive (test) data is included, e.g. data based on real people or cases.
* Current documentation (see [Em002-2] Annexes D.1. and D.2.)
* Delete unnecessary files or outdated documents.
* Check code for secrets/credentials.footnote:[https://www.ncsc.admin.ch/ncsc/en/home/aktuell/im-fokus/2022/git.html]
* Conduct targeted security tests and subsequently establish a (public) bug bounty programme.footnote:[https://www.ncsc.admin.ch/ncsc/en/home/infos-fuer/infos-it-spezialisten/themen/bug-bounty-programme.html]
* Review all libraries used to ensure licences are present and corresponding lists (attributions) have been created.
* Description of the deployment (CI/CD pipelinefootnote:[https://en.wikipedia.org/wiki/CI/CD]) and possibly setup of a demo instance.

|☐
a|
Licence selection

* Check for any dependencies on existing licences.
* For third-party code, check terms of use for compatibility with intended licence and replace code if necessary.
* Select the appropriate licence using the guide 'Em002-3 OSS Licensing Guidelines' (primary recommendations are AGPL for copyleft and MIT for permissive).

Selected licence and justification

|☐
a|
The documentation is stored with the source code (see [Em002-2] Annex D.1.)

Justification/storage location

|☐
a|
The documentation addresses both end users and technical professionals.

List of the central documentation

|☐
a|
Detailed documentation of the source code (OSS specific)

Important standard documentation (README, LICENSE, CONTRIBUTING, etc.) is available.

|☐
a|
The source code, including history, contains no sensitive, protected or confidential personal data. Or the history has been completely deleted. (see [Em002-2] Annex E.2.)

Explanation of review (if not filed as separate document)

|☐
a|
It has been clarified with the supplier and all involved developers within the Federal Administration whether author information (names, email addresses) may be published. +
Alternatively, the source code including history has been cleaned/anonymised.

|☐
a|
The libraries used by the project are compatible with the project's licence.

Explanation of review (if not filed as separate document)

|☐
|The project uses a package manager to manage its dependencies.

|☐
|The project declares its licence in the corresponding descriptor of the package manager. Creation of a Software Bill of Materials (SBOM), which lists all open source components used.

|☐
a|
The source code contains a _THIRD-PARTY-LICENSES.md_ file listing for each library used: the project name of the library, the homepage of the library, the SPDX identifier of the library's licence, and a link to the library's licence.

|☐
|For applications, an 'About' dialogue is available that references the _THIRD-PARTY-LICENSES.md_ file.

|☐
|As part of the code review process, it is ensured that the _THIRD-PARTY-LICENSES.md_ file is updated with every change to the libraries.

|===

== Concluding remarks

Comments and references to other relevant documents

[cols="1"]
|===
a|

|===

*Filing of form*

Please file this form with the project documentation and/or in accordance with the specifications of your authority (organisational unit).

*Licence of the checklist template: CC0 1.0 Universal*

This document is published under the https://creativecommons.org/publicdomain/zero/1.0/[_CC0 licence_]. It may be freely used, modified and distributed, including for commercial purposes and in any format.
