= Tools for Publishing Open Source Software
:lang: en
:govpress-style: report
:govpress-front-block: report
:classification:
:title-logo: logo-ch-black.svg
:title-logo-base: black
:title-logo-line1: Federal Chancellery FCh
:title-logo-line2: Office
:title-logo-line3:
:title-page:
:pdf-theme: basic
:toc:
:sectnums:
:toclevels: 3
:sectnumlevels: 3
:experimental:
:revnumber: 1.0
:revdate: 14.09.2026
:url-repo: https://github.com/swiss/opensource-guidelines/tree/main

Federal agencies are required to disclose the source code of software they develop or have developed to fulfill their duties. They must allow anyone to use, further develop, and distribute the software without charging licensing fees. This requirement is outlined in Article 9 of the Federal Act on the Use of Electronic Means for Fulfilling Administrative Tasks (EMOTA). Responsibility for implementation lies with the individual agencies. The Federal Chancellery provides suitable tools to assist federal agencies in meeting this requirement.

== What is it about?

When publishing open-source software, questions regarding legal matters, licenses, security, organization, and costs need to be addressed. Depending on the specific use case, there are variations and limitations to consider. The level of knowledge required to implement the legal requirement varies within the federal administration based on experience. For this reason, the Federal Chancellery has created tools and checklists to provide support and guidance for decision-making.

== Who is responsible?

The individual agencies are responsible for implementation. The Federal Chancellery provides suitable tools to assist federal agencies in this process.

== What tools are available?

The following tools are available in the form of guidelines, instructions, checklists, fact sheets, and FAQs:

link:en/em002.adoc[Em002 Strategic Guidelines for Open Source Software in the Federal Administration] (05.05.2026)

link:en/em002-1.adoc[Em002-1 Practical Guidelines for Open Source Software in the Federal Administration] (05.05.2026)

link:en/em002-2.adoc[Em002-2 Instructions for Publishing OSS] (05.05.2026)

link:en/em002-2-1-checklist-oss-preliminary-assessment.adoc[Em002-2.1 Preliminary Assessment Checklist] (ODT, 05.05.2026)

link:en/em002-2-2-checklist-oss-analysis-and-preparation.adoc[Em002-2.2 Analysis and Preparation Checklist] (ODT, 92 kB, 05.05.2026)

link:en/em002-2-3-checklist-oss-release-and-publication.adoc[Em002-2.3 Release and Publication Checklist] (ODT, 93 kB, 05.05.2026)

link:en/em002-3.adoc[Em002-3 OSS Licensing Guidelines] (05.05.2026)

link:en/em002-4.adoc[Em002-4 OSS Community Guidelines] (05.05.2026)

link:en/em002-4-1-checklist-oss-community.adoc[Em002-4.1 OSS Community Checklist] (ODT, 94 kB, 05.05.2026)

link:en/em002-5.adoc[Em002-5 EMOTA and OSS Factsheet] (06.05.2026)

link:en/em002-6.adoc[Em002-6 FAQ on OSS and Art. 9 EMOTA] (05.05.2026)

link:en/em002-7.adoc[Em002-7 OSS Guideline: Applying Article 9 of Federal Act on the Use of Electronic Means for Fulfilling Administrative Tasks (EMOTA)] (05.05.2026)

https://www.bk.admin.ch/dam/bk/de/dokumente/dti/OSS/oss_merkblatt_kbb_beschaffung_artikel9_embag.pdf.download.pdf/Merkblatt_KBB_Beschaffung-Software-Art9-EMBAG_de.pdf[Merkblatt KBB Beschaffung Software Artikel 9 EMBAG] (PDF, 177 kB, 13.08.2025) only available in German, French and Italian

== Further information

https://www.admin.ch/gov/de/start/dokumentation/medienmitteilungen.msg-id-98828.html[Federal Act on the Use of Electronic Means to Carry Out Official Tasks EMOTA] only available in German

http://www.opensource.admin.ch/[OSS Catalogue]
